#!/bin/bash
set -euo pipefail
HERE=$(dirname "${BASH_SOURCE[0]}")

domain_name="${1:?enter domain name you have hosted at route53}"
zone_id=$("$HERE"/zone-id "$domain_name")

aws route53 list-resource-record-sets --hosted-zone-id "$zone_id" \
  | python "$HERE/zone2dot.py"

